sub init()
    m.top.setFocus(true)
    m.mainLabel = m.top.findNode("mainLabel")
    'change the color
    m.mainLabel.color = "0xFFFFFF"
    'make the text really big
    m.mainLabel.font.size = 100

    m.arr = [
        m.mainLabel
    ]
    promise = reftracker.findNodeRefsById({
        id: "mainLabel"
    })
    reftracker.promises.chain(promise).then(function(result)
        print result
    end function)
end sub
