sub init()
    m.top.setFocus(true)
    m.mainLabel = m.top.findNode("mainLabel")
    'change the color
    m.mainLabel.color = "0xFFFFFF"
    'make the text really big
    m.mainLabel.font.size = 100

    m.arr = [
        m.mainLabel
    ]
    reftracker.findNodeRefsById({
        id: "mainLabel"
    }, function(result)
        print "nodes for ID", FormatJson(result, &h0200)
    end function)
end sub
